### ISSUE TITLE
It hangs when processing https://www.edd.ca.gov/Jobs_and_Training/warn/WARN_Report.xlsx

### ISSUE THREAD

**Issue by chfw** [pyexcel/pyexcel-xlsx#40]
reference: https://github.com/pyexcel/pyexcel-xls/issues/34

**Comment by chfw** [comment]
it is reported here: https://bitbucket.org/openpyxl/openpyxl/issues/1473/openpyxl-hangs-up-when-opening-a

**Comment by chfw** [comment]
@suiyuan2009, please follow up the issue on this thread.

**Comment by Themanwithoutaplan** [comment]
openpyxl doesn't hang but does take a long time to open the file. The reason is that the file contains over 42000 merged cell ranges which also have borders and openpyxl does some work to remove ambiguity from the worksheet, so that it is clear that D5 contains nothing.

This is an example of a very poorly formatted worksheet that merges cells so that two unrelated and different sized tables appear under each other.

If you open the file in read-only mode (analogous to use xlrd), it will read much faster.

**Comment by chfw** [comment]
@Themanwithoutaplan thanks for the update.

With pyexcel-xlsx, it is possible to turning on read-only by turning off both flags: `skip_hidden_row_and_column=False, skip_hidden_sheets=False`. So the following code will work as intended (like xlrd)

```
>>> import pyexcel as p
>>> p.get_array(file_name='WARN_Report.xlsx', skip_hidden_row_and_column=False, skip_hidden_sheets=False)
```

Because above flags were turned on by default, so it is a bit confusing. I indeed have noted them in the readme, however, I think I will toggle the default flags in the next release. 


```
Please note:

skip_hidden_row_and_column will get a penalty where read_only mode cannot be used.
```

**Comment by chfw** [comment]
https://openpyxl.readthedocs.io/en/stable/changes.html#id9

please pin your openpyxl version to 3.0.4
